name: Valgrind
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  valgrind:
    name: Valgrind
    uses: M3_Wiper_Control_System/valgrind-action/.github/workflows/Valgrind.yml@3.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}
